name: Sync SDK

on:
  workflow_dispatch:
    inputs:
      sdk_tag:
        description: 'New SDK Tag'
        required: true
        type: string

jobs:
  sync:
    uses: agent-hub-org/deploy/.github/workflows/reusable-sync.yml@main
    with:
      agent_name: agent-research
      sdk_tag: ${{ inputs.sdk_tag }}
    secrets:
      ORG_PAT: ${{ secrets.ORG_PAT }}
